### ISSUE TITLE
Deploy the Date Annotator Stub using CF template

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/aws-cloudformation#3]
The Date Annotator Stub is the vanilla API service generated by the OpenAPI Generator. It does nothing more than returning "do some magic!". I rely on this service to provide a step-by-step guide to develop an NLP Tool.

Deployment procedure:
1. Get this [docker-compose.yml](https://github.com/nlpsandbox/date-annotator-stub/blob/develop/docker-compose.yml)
2. `docker-compose up -d`

This stack of Docker container relies on images that have a fixed version number (no latest, edge or nightly tag).

- This stack of Docker container is listening to the port 80 of the host.
- The EC2 running this service should be placed behind a load balancer that redirect port 443  (HTTPS) to port 80 of the EC2.
- This EC2 should be publicly accessible - via its load balancer - using the domain name: `date-annotator-stub.nlpsandbox.io`.
- Recommended EC2: t2.nano

**Comment by thomasyu888** [comment]
Will close after adding route53

**Comment by tschaffter** [comment]
Route53 will be added as part of #9
