### ISSUE TITLE
Deploy the Date Annotator example using CF template

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/aws-cloudformation#4]
The Date Annotator Example is the only example implementation that we will deploy as an example. This example is used in the documentation of the NLP Sandbox.

Deployment procedure:
1. Get this [docker-compose.yml](https://github.com/nlpsandbox/date-annotator-example/blob/develop/docker-compose.yml)
2. `docker-compose up -d`

This stack of Docker container relies on images that have a fixed version number (no latest, edge or nightly tag).

- This stack of Docker container is listening to the port 80 of the host.
- The EC2 running this service should be placed behind a load balancer that redirect port 443  (HTTPS) to port 80 of the EC2.
- This EC2 should be publicly accessible - via its load balancer - using the domain name: `date-annotator-example.nlpsandbox.io`.
- Recommended EC2: t2.nano

**Comment by thomasyu888** [comment]
Will close after creating the link in Route53

**Comment by tschaffter** [comment]
Route53 will be added as part of #9
